set(ONNX_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
include_directories(${ONNX_INCLUDE_DIRS})

if (APPLE)
    message("配置MACOS ONNX 路径")
    link_directories(${CMAKE_CURRENT_SOURCE_DIR}/onnx/macos)
    set(ONNX_LIBS onnxruntime)
elseif (WIN32)
    message("配置WINDOWS ONNX 路径")
    link_directories(${CMAKE_CURRENT_LIST_DIR}/windows)
    file(GLOB ALL_ONNX_STATIC_LIBS ${CMAKE_CURRENT_LIST_DIR}/windows/*.lib)
    set(ONNX_LIBS ${ALL_ONNX_STATIC_LIBS})
elseif (UNIX)
    message("配置LINUX ONNX 路径")
    link_directories(${CMAKE_CURRENT_SOURCE_DIR}/onnx/linux)
    set(ONNX_LIBS onnxruntime)
endif ()

set(ONNX_FOUND TRUE)