if (APPLE)
    set(NCNN_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/macos/include")
    include_directories(${NCNN_INCLUDE_DIRS})
    message("配置macOS ncnn 路径: ${CMAKE_CURRENT_LIST_DIR}/macos/lib/cmake/ncnn")
    set(ncnn_DIR "${CMAKE_CURRENT_LIST_DIR}/macos/lib/cmake/ncnn")
elseif (WIN32)
    if (CMAKE_CL_64)
        message("配置WINDOWS ncnn x64 路径: ${CMAKE_CURRENT_LIST_DIR}/windows-x64/lib/cmake/ncnn")
        set(ncnn_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x64/lib/cmake/ncnn")
        set(NCNN_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/windows-x64/include")
    else ()
        message("配置WINDOWS ncnn x86 路径: ${CMAKE_CURRENT_LIST_DIR}/windows-x86/lib/cmake/ncnn")
        set(ncnn_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x86/lib/cmake/ncnn")
        set(NCNN_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/windows-x86/include")
    endif ()
    include_directories(${NCNN_INCLUDE_DIRS})
elseif (UNIX)
    set(NCNN_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/linux/include")
    include_directories(${NCNN_INCLUDE_DIRS})
    message("配置Linux ncnn 路径: ${CMAKE_CURRENT_LIST_DIR}/linux/lib/cmake/ncnn")
    set(ncnn_DIR "${CMAKE_CURRENT_LIST_DIR}/linux/lib/cmake/ncnn")
endif ()

