if (APPLE)
    message("配置macOS OnnxRuntime 路径: ${CMAKE_CURRENT_LIST_DIR}/macos")
    set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/macos")
elseif (WIN32)
    if (CMAKE_CL_64)
        message("配置WINDOWS OnnxRuntime x64 路径: ${CMAKE_CURRENT_LIST_DIR}/windows-x64")
        set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x64")
    else ()
        message("配置WINDOWS OnnxRuntime x86 路径: ${CMAKE_CURRENT_LIST_DIR}/windows-x86")
        set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x86")
    endif ()
elseif (UNIX)
    message("配置Linux OnnxRuntime 路径: ${CMAKE_CURRENT_LIST_DIR}/linux")
    set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/linux")
endif ()

