set(NCNN_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
include_directories(${NCNN_INCLUDE_DIRS})

if (APPLE)
    message("配置MACOS NCNN 路径")
    link_directories(${CMAKE_CURRENT_LIST_DIR}/macos)
    file(GLOB ALL_NCNN_STATIC_LIBS ${CMAKE_CURRENT_LIST_DIR}/macos/*.a)
    set(NCNN_LIBS ${ALL_NCNN_STATIC_LIBS})
elseif (WIN32)
    message("配置WINDOWS ONNX 路径")
    link_directories(${CMAKE_CURRENT_LIST_DIR}/windows)
    file(GLOB ALL_NCNN_STATIC_LIBS ${CMAKE_CURRENT_LIST_DIR}/windows/*.lib)
    set(NCNN_LIBS ${ALL_NCNN_STATIC_LIBS})
elseif (UNIX)
    message("配置LINUX ONNX 路径")
    link_directories(${CMAKE_CURRENT_LIST_DIR}/linux)
    file(GLOB ALL_NCNN_STATIC_LIBS ${CMAKE_CURRENT_LIST_DIR}/linux/*.a)
    set(NCNN_LIBS ${ALL_NCNN_STATIC_LIBS})
endif ()

set(NCNN_FOUND TRUE)